FROM golang:1.11.0
WORKDIR /go/src/github.com/nisargthakkar/final-project-nisargthakkar-remote-configuration/userclient
COPY userclient .
COPY pb ../pb

RUN go get -v ./...
RUN go install -v ./...

EXPOSE 8001
CMD ["userclient"]
