FROM golang:1.11.0
WORKDIR /go/src/github.com/nisargthakkar/final-project-nisargthakkar-remote-configuration/server
COPY server .
COPY pb ../pb

RUN go get -v ./...
RUN go install -v ./...

EXPOSE 3000
CMD ["server"]
