FROM python:3

WORKDIR /usr/src/app

COPY front-tier/front-tier-app.py .
COPY front-tier/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD [ "python", "-u", "./front-tier-app.py" ]